import { _Any } from './any';
import { _Box } from './box';
import { setShapesFactory } from './common';
import { _Cone } from './cone';
import { _Cut } from './cut';
import { _Cylinder } from './cylinder';
import { _Extrude } from './extrude';
import { _Fuse } from './fuse';
import { _Chamfer } from './chamfer';
import { _Fillet } from './fillet';
import { _Intersection } from './intersection';
import { _loadObjectFile } from './loadObjectFile';
import { operatorCache } from './operatorCache';
import { _PostOperator } from './postOperator';
import { _SketchObject } from './sketchObject';
import { _Sphere } from './sphere';
import { _Torus } from './torus';
export const Any = operatorCache('Part::Any', _Any);
export const Box = operatorCache('Part::Box', _Box);
export const Cylinder = operatorCache('Part::Cylinder', _Cylinder);
export const Sphere = operatorCache('Part::Sphere', _Sphere);
export const Cone = operatorCache('Part::Cone', _Cone);
export const Torus = operatorCache('Part::Torus', _Torus);
export const SketchObject = operatorCache('Sketcher::SketchObject', _SketchObject);
export const Cut = operatorCache('Part::Cut', _Cut);
export const Fuse = operatorCache('Part::MultiFuse', _Fuse);
export const Intersection = operatorCache('Part::MultiCommon', _Intersection);
export const Extrude = operatorCache('Part::Extrusion', _Extrude);
export const Chamfer = operatorCache('Part::Chamfer', _Chamfer);
export const Fillet = operatorCache('Part::Fillet', _Fillet);
export const ObjectFile = operatorCache('ObjectFile', _loadObjectFile);
export function initShapesFactory() {
    setShapesFactory('Part::Any', Any);
    setShapesFactory('Part::Box', Box);
    setShapesFactory('Part::Cylinder', Cylinder);
    setShapesFactory('Part::Sphere', Sphere);
    setShapesFactory('Part::Cone', Cone);
    setShapesFactory('Part::Torus', Torus);
    setShapesFactory('Part::Cut', Cut);
    setShapesFactory('Part::MultiFuse', Fuse);
    setShapesFactory('Part::Extrusion', Extrude);
    setShapesFactory('Part::MultiCommon', Intersection);
    setShapesFactory('Part::Chamfer', Chamfer);
    setShapesFactory('Part::Fillet', Fillet);
    setShapesFactory('Sketcher::SketchObject', SketchObject);
    setShapesFactory('Post::Operator', _PostOperator);
}
export { getShapesFactory } from './common';
