/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Any
 */
export interface IAny {
  /**
   * The string content of the object
   */
  Content: string;
  Type: "brep" | "step" | "stl";
  /**
   * The color of the object
   */
  Color?: string;
  /**
   * Placement of the object
   */
  Placement?: {
    /**
     * Position
     */
    Position: number[];
    /**
     * Rotation Axis
     */
    Axis: number[];
    /**
     * Rotation Angle (degrees)
     */
    Angle: number;
  };
}
