/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Box
 */
export interface IBox {
  /**
   * The length of the box (dX)
   */
  Length: number;
  /**
   * The width of the box (dY)
   */
  Width: number;
  /**
   * The height of the box (dZ)
   */
  Height: number;
  /**
   * The color of the box
   */
  Color?: string;
  /**
   * Placement of the object
   */
  Placement: {
    /**
     * Position
     */
    Position: number[];
    /**
     * Rotation Axis
     */
    Axis: number[];
    /**
     * Rotation Angle (degrees)
     */
    Angle: number;
  };
}
