/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Fillet
 */
export interface IFillet {
  /**
   * The name of input object
   */
  Base: string;
  Edge: number | number[];
  /**
   * The radius for the fillet
   */
  Radius: number;
  /**
   * The color of the fillet
   */
  Color?: string;
  /**
   * Placement of the object
   */
  Placement: {
    /**
     * Position
     */
    Position: number[];
    /**
     * Rotation Axis
     */
    Axis: number[];
    /**
     * Rotation Angle (degrees)
     */
    Angle: number;
  };
}
