/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Sphere
 */
export interface ISphere {
  /**
   * The radius of the sphere
   */
  Radius: number;
  /**
   * First angle defining a spherical segment
   */
  Angle1: number;
  /**
   * Second angle defining a spherical segment
   */
  Angle2: number;
  /**
   * The angle between the radii lying within the bounding semidisks
   */
  Angle3: number;
  /**
   * The color of the sphere
   */
  Color?: string;
  /**
   * Placement of the object
   */
  Placement: {
    /**
     * Position
     */
    Position: number[];
    /**
     * Rotation Axis
     */
    Axis: number[];
    /**
     * Rotation Angle (degrees)
     */
    Angle: number;
  };
}
