/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Torus
 */
export interface ITorus {
  /**
   * The distance from the center of the pipe to the center of the torus
   */
  Radius1: number;
  /**
   * The radius of the pipe
   */
  Radius2: number;
  /**
   * First angle to create a torus ring segment
   */
  Angle1: number;
  /**
   * Second angle to create a torus ring segment
   */
  Angle2: number;
  /**
   * Angle to create a torus pipe segment
   */
  Angle3: number;
  /**
   * The color of the torus
   */
  Color?: string;
  /**
   * Placement of the object
   */
  Placement: {
    /**
     * Position
     */
    Position: number[];
    /**
     * Rotation Axis
     */
    Axis: number[];
    /**
     * Rotation Angle (degrees)
     */
    Angle: number;
  };
}
