import { IAnnotation, IDict } from '@jupytercad/schema';
import { User } from '@jupyterlab/services';
import * as React from 'react';
import { MainViewModel } from './mainviewmodel';
interface IProps {
    viewModel: MainViewModel;
}
interface IStates {
    id: string;
    loading: boolean;
    remoteUser?: User.IIdentity | null;
    annotations: IDict<IAnnotation>;
    firstLoad: boolean;
    wireframe: boolean;
    transform: boolean;
    clipEnabled: boolean;
    explodedViewEnabled: boolean;
    explodedViewFactor: number;
    rotationSnapValue: number;
    translationSnapValue: number;
    transformMode: string | undefined;
}
export declare class MainView extends React.Component<IProps, IStates> {
    constructor(props: IProps);
    componentDidMount(): void;
    componentDidUpdate(oldProps: IProps, oldState: IStates): void;
    componentWillUnmount(): void;
    addContextMenu: () => void;
    sceneSetup: () => void;
    private _createAxesHelper;
    private _createViewHelper;
    animate: () => void;
    resizeCanvasToDisplaySize: () => void;
    generateScene: () => void;
    private lookAtPosition;
    private updateCameraRotation;
    private _updateAnnotation;
    private _handleSettingsChange;
    private _onPointerMove;
    private _pick;
    private _onClick;
    private _onKeyDown;
    private _shapeToMesh;
    private _updateRefLength;
    private _objToMesh;
    private _workerBusyHandler;
    private _requestRender;
    private _updatePointersScale;
    private _createPointer;
    private _updateSelected;
    private _updateTransformControls;
    private _onSharedMetadataChanged;
    private _onClientSharedStateChanged;
    private _onSharedOptionsChanged;
    private _onViewChanged;
    get explodedViewEnabled(): boolean;
    private _setupExplodedView;
    private _updateCamera;
    private _updateSplit;
    initSlider(display: boolean): void;
    private _exportSceneToGLB;
    private _updateClipping;
    private _handleThemeChange;
    private _handleWindowResize;
    private _computeAnnotationPosition;
    private _handleSnapChange;
    private _handleExplodedViewChange;
    render(): JSX.Element;
    private _divRef;
    private _mainViewRef;
    private _model;
    private _mainViewModel;
    private _pointer;
    private _syncPointer;
    private _selectedMeshes;
    private _meshGroup;
    private _boundingGroup;
    private _explodedView;
    private _explodedViewLinesHelperGroup;
    private _clipSettings;
    private _clippingPlaneMeshControl;
    private _clippingPlaneMesh;
    private _clippingPlane;
    private _clippingPlanes;
    private _edgeMaterials;
    private _currentSelection;
    private _scene;
    private _ambientLight;
    private _camera;
    private _cameraLight;
    private _raycaster;
    private _renderer;
    private _requestID;
    private _geometry;
    private _refLength;
    private _sceneAxe;
    private _controls;
    private _mouseDrag;
    private _clipPlaneTransformControls;
    private _transformControls;
    private _pointer3D;
    private _clock;
    private _targetPosition;
    private _viewHelper;
    private _viewHelperDiv;
    private _collaboratorPointers;
    private _contextMenu;
    private _loadingTimeout;
    private _sliderPos;
    private _slideInit;
    private _sceneL;
    private _cameraL;
    private _keyDownHandler;
}
export {};
