/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Part::Extrusion
 */
export interface IExtrusion {
  /**
   * Shape to extrude
   */
  Base: string;
  /**
   * Direction of extrusion
   */
  Dir: number[];
  /**
   * Length of extrusion along the direction
   */
  LengthFwd: number;
  /**
   * Length of extrusion against the direction
   */
  LengthRev: number;
  /**
   * If true, creating a solid
   */
  Solid: boolean;
  /**
   * The color of the extrusion
   */
  Color?: string;
  /**
   * Placement of the object
   */
  Placement: {
    /**
     * Position
     */
    Position: number[];
    /**
     * Rotation Axis
     */
    Axis: number[];
    /**
     * Rotation Angle (degrees)
     */
    Angle: number;
  };
}
