/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Placement of the object
 */
export interface Placement {
  /**
   * Position
   */
  Position: number[];
  /**
   * Rotation Axis
   */
  Axis: number[];
  /**
   * Rotation Angle (degrees)
   */
  Angle: number;
}
