/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Post::Operator
 */
export interface IPostOperator {
  /**
   * The name of input object
   */
  Object: string;
  /**
   * The filetype for export (Brep/Stl)
   */
  Type?: "BREP" | "STL";
  [k: string]: any;
}
